import { TEAM_ROLE, type TeamRole } from "@/constants/roles";

export const PERMISSION = {
  VIEW_WORK_ITEM: "VIEW_WORK_ITEM",
  VIEW_ACTIVITY: "VIEW_ACTIVITY",

  CREATE_WORK_ITEM: "CREATE_WORK_ITEM",
  EDIT_WORK_ITEM: "EDIT_WORK_ITEM",
  CHANGE_PRIORITY: "CHANGE_PRIORITY",

  TRANSITION_WORK_ITEM: "TRANSITION_WORK_ITEM",

  ASSIGN_SELF: "ASSIGN_SELF",
  ASSIGN_OTHERS: "ASSIGN_OTHERS",

  MANAGE_TEAM_MEMBERS: "MANAGE_TEAM_MEMBERS",
} as const;

export type Permission =
  (typeof PERMISSION)[keyof typeof PERMISSION];

export const ROLE_PERMISSIONS: Record<
  TeamRole,
  readonly Permission[]
> = {
  [TEAM_ROLE.MEMBER]: [
    PERMISSION.VIEW_WORK_ITEM,
    PERMISSION.VIEW_ACTIVITY,

    PERMISSION.CREATE_WORK_ITEM,
    PERMISSION.EDIT_WORK_ITEM,
    PERMISSION.CHANGE_PRIORITY,

    PERMISSION.TRANSITION_WORK_ITEM,

    PERMISSION.ASSIGN_SELF,
  ],

  [TEAM_ROLE.LEAD]: [
    PERMISSION.VIEW_WORK_ITEM,
    PERMISSION.VIEW_ACTIVITY,

    PERMISSION.CREATE_WORK_ITEM,
    PERMISSION.EDIT_WORK_ITEM,
    PERMISSION.CHANGE_PRIORITY,

    PERMISSION.TRANSITION_WORK_ITEM,

    PERMISSION.ASSIGN_SELF,
    PERMISSION.ASSIGN_OTHERS,

    PERMISSION.MANAGE_TEAM_MEMBERS,
  ],
};

export function roleHasPermission(
  role: TeamRole,
  permission: Permission,
): boolean {
  return ROLE_PERMISSIONS[role].includes(permission);
}